# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kqoLRWBWS0tTUVEN8t_izhLlxwaQ7oE
"""

import os
import pandas as pd

# Criar pasta 'data' se não existir
os.makedirs("data", exist_ok=True)

# Simulando dados
data = {
    "driver": ["Verstappen", "Hamilton", "Leclerc", "Norris"],
    "team": ["Red Bull", "Mercedes", "Ferrari", "McLaren"],
    "position": [1, 2, 3, 4],
    "laps": [58, 58, 58, 58],
    "time_seconds": [5400, 5420, 5450, 5480]
}

df = pd.DataFrame(data)

# Salvar CSV
df.to_csv("data/sample_f1_data.csv", index=False)

print("Arquivo criado com sucesso!")
